友链:
  XAOXUU: https://xaoxuu.com/atom.xml
  LonelyGod: https://hin.cool/atom.xml
  By_Xb: https://byxiaobian.github.io/atom.xml
  枋柚梓的猫会发光: https://inkss.cn/atom.xml #https://raw.githubusercontent.com/inkss/inkss.github.io/main/atom.xml
  FANTASY: https://blog.tigerxly.com/feed/atom
  HKLin: /friends/HKLin

Hexo:
  DIYgod: /hexo/next/diygod.me
  Mimi: /hexo/next/zhangshuqiao.org
  Xecades: https://blog.xecades.xyz/atom.xml
  yunyoujun: https://www.yunyoujun.cn/atom.xml
  ChenYFan: https://raw.githubusercontent.com/ChenYFan/blog/gh-pages/atom.xml

These Blogs:
  Github: https://github.blog/all.atom
  Cloudflare: https://blog.cloudflare.com/rss/
  RSS3.fun: https://rss3.fun/tag/chinese/rss/

twitter:
  DIYgod: /twitter/user/Diygod
  Github: /twitter/user/Github
  Huawei: /twitter/user/HUAWEI
  Cloudflare: /twitter/user/Cloudflare
  CloudflareDev: /twitter/user/CloudflareDev

Github Trending:
  python: /github/trending/daily/python
  javascript: /github/trending/daily/javascript
  any: /github/trending/daily/any


二次元:
  三界异次元: /3ycy/home
  pixiv week: /pixiv/ranking/week
  pixiv day: /pixiv/ranking/day

知乎:
  知乎热榜: /zhihu/hotlist
  知乎想法热榜: /zhihu/pin/hotlist

发现:
  每日精选: /cnu/selected
  自然: /cnu/discovery/recent/自然
  天文: /bjp/apod
  1X: /1x
  dailyart: /dailyart/zh
  NASA: /nasa/apod
  bing: /bing 

阅读:
  All Poetry: /allpoetry/newest

Status of Monitors: https://rss.uptimerobot.com/u991833-f82a522f0ede9bf2e108279aaf437bcd



